### ISSUE TITLE
[feature-request] Implement a scheduling system for ResearchKit tasks (+CareKit)

### ISSUE THREAD

**Issue by ssgutierrez42** [CardinalKit/CardinalKit#31]
**Is your feature request related to a problem? Please describe.**
Implement a system by which RK tasks can be scheduled and shown to patients at specific days or times. 

**Describe the solution you'd like**
Use CareKit to define a care plan, and schedule a series of tasks to occur over a set amount of time. 
https://developer.apple.com/carekit/

Bonus: leverage Firestore to enable the download of the latest schedule via your CardinalKit app.

**NOTE: interest on features is gaged using reactions on this first post: e.g.  👍**

**Comment by hershman** [comment]
👍 #back_track will likely tackle this.  Will also need to support multiple schedules for a remote RCT.

**Comment by varunshenoy** [comment]
Awesome — we're looking forward to seeing a pull request! For bonus points: make tasks easy to schedule directly from the `StudyTableItem.swift` file!

**Comment by hjsonghjsong** [comment]
Hello, I was the back_track team on the hackathone. My team and myself would like to implement this feature using OCKTask (because OCKTask has built-in schedule in it). Once we define OCKTask  (hopefully in StudyTableItem.swift), we will change StudiesUI.swift to display the OCKTask using SwiftUI views  (such as CareKit.SimpleTaskView, CareKit.InstructionsTaskView etc). Let me know if you have any comments on it.
